# Netlify configuration for Wedding Invitation
[build]
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = "dist"

# Environment variables (alternative method)
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
